### ISSUE TITLE
About factory provider design, why can not direct set as singleton.

### ISSUE THREAD

**Issue by Moln** [Microsoft/tsyringe#14]
```typescript
class FooList {
  public void add(str: string) {}
}
di.register<FooList>(
  FooList, 
  {
    useFactory: (d) => {
      const obj = new FooList();
      obj.add('foo1');
      return obj;
    }
  },
 {singleton: true}
); 

const result1 = di.resolve<FooList>(FooList);
const result2 = di.resolve<FooList>(FooList);

console.log(result1 === result2); 
```

### Expected Behavior

Console result: `true`

### Current Behavior

```
Throw: Cannot use {singleton: true} with ValueProviders or FactoryProviders
```

### Solution

Use TokenProvider again.

```typescript
di.register<FooList>(
  'FooListFactory', 
  {
    useFactory: (d) => {
      const obj = new FooList();
      obj.add('foo1');
      return obj;
    }
  }
);
di.register<FooList>(
  FooList, 
  {useToken:  'FooListFactory',},
  {singleton: true}
);
```

But, why can not direct set it.

Is it a bug ? Or some problem of design?

**Comment by Xapphire13** [comment]
This is by design, singleton/transient doesn't really make much sense for a factory. Since with a factory, we want the factory method to run _each time_ we resolve a token.

If you want your factory to return a singleton, you can use either the built in [`instanceCachingFactory`](https://github.com/Microsoft/tsyringe/blob/6d96044f217218ac0c073840b59350fd25b49f9b/src/factories.ts#L5-L15) or set `useCaching` on the [`predicateAwareClassFactory`](https://github.com/Microsoft/tsyringe/blob/6d96044f217218ac0c073840b59350fd25b49f9b/src/factories.ts#L17-L38). Alternatively, if you use a custom factory, you can implement the caching yourself.

**Comment by Moln** [comment]
Get it. Thanks for your answer.

Before using this, I am using c# dependency injection ([`AddSingleton(IServiceCollection, Type, Func<IServiceProvider,Object>)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions.addsingleton?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_ServiceCollectionServiceExtensions_AddSingleton__2_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_Func_System_IServiceProvider___1__)).

That’s why I have this question.

**Comment by spikyjt** [comment]
I appreciate this is old, but who says we want to use a factory to instantiate an instance _each time_ we resolve a token? What if we want a singleton which requires some specific set up (i.e. not just mapped to any old instance of a class) but we don't want to do that set up at registration, preferring to delay it until first resolution? This could be particularly useful if the set up is heavy and we either don't want it to happen at the start or even at all if unused. Perhaps there is another way to achieve this?

**Comment by bityardigans** [comment]
I would like to second the comment above; effectively your solution would be the same as applying lifecycle to factory- you just added and extra step reqrenuiring 2 registration to do what you could do in 1 signature. It would be no different than defaulting lifecycle to null or every request as a scope if not supplied in the registration options. So instead of making it easier and readable its now obfuscation and doesn't stop someone from injecting the factory and having it run every time when you just want a singleton. I dunno...would be nice if we did not have to do that workaround.

**Comment by mikl** [comment]
Ditto here, I’ve been using useFactory to construct non-class things, like this:

```typescript
function loggerFactory(conf: Configuration) {

  return winston.createLogger({
    transports: [
      new winston.transports.Console({
        format,
        level: conf.get<string>('logLevel')
      })
    ]
  })
}

container.register<winston.Logger>(LOGGER, {
  useFactory: (dc) => loggerFactory(dc.resolve(Configuration))
})
```

Having to wrap that in `instanceCachingFactory` does work, but it would be better ergonomics if there was an option for this.

**Comment by tdias25** [comment]
Thanks, @mikl  
`instanceCachingFactory` did work for me, but i'm wondering if that is the proper way of using it

**Comment by llucasspot** [comment]
Hi, I see you said years ago : 

"This is by design, singleton/transient doesn't really make much sense for a factory. Since with a factory, we want the factory method to run each time we resolve a token."

=> i dont realy understand your words here, why it doesn't really make much sense ?
Sometimes we want to make singleton services where his implementation need a other service from the container

exemple with cart service : 

registerByValue(CartApiServiceInterface, (container) => {
    return new LocalStorageCartApiService();
  });
 registerByFactory(CartService, (container) => {
    return new CartService(container.getInstance(CartApiServiceInterface));
  });
  
with CartService the fonctional service and CartApiServiceInterface the technical adaptor that can be change if we want to have a api by local storage or web api storage bh exemple

**Comment by llucasspot** [comment]
that is sad to be force to use `instanceCachingFactory` to overcome this issue

```typescript
useFactory: instanceCachingFactory((container) => {
                return useFactory(container);
            }),
```

this sould be a "buildin" feature like the others with the options `LifeCycle`
