### ISSUE TITLE
How to use with other decorators?

### ISSUE THREAD

**Issue by user753** [microsoft/tsyringe#54]
```
function logNew() {
  return <T extends constructor<any>>(constructor: T) => {
    return class extends constructor {
      constructor(...args: any[]) {
        super(...args);
        console.log("CREATED", args)
      }
    }
  };
}

class Foo {
  value = "foo"
}

@logNew()
@injectable()
class Bar {
  constructor(foo: Foo){
    console.log(foo.value)
  }
}

const bar = container.resolve(Bar)
```
`foo` is undefined

**Comment by user753** [comment]
@skiptirengu this code doesn't work for me
```
Class constructor Bar cannot be invoked without 'new'
```

**Comment by skiptirengu** [comment]
Can you provide more info on this error? I created a test case for it and seems to be working fine.

![image](https://user-images.githubusercontent.com/5993725/64881075-36f04100-d630-11e9-84a6-7e314dc21890.png)

**Comment by user753** [comment]
@skiptirengu I use babel with https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata and It seems `autoInjectable` doesn't work with them. 
The error is on this code
```
c:/projects/frontend/node_modules/tsyringe/dist/esm5/decorators/auto-injectable.js:19
return _super.apply(this, args.concat(paramInfo.slice(args.length)
```

**Comment by skiptirengu** [comment]
Probably related to [this section](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata#usage-with-inversifyjs) on the `babel-plugin-transform-typescript-metadata` documentation.

**Comment by lrembacz** [comment]
@skiptirengu, @user753 
Had the same issue but only when I was using @babel/typescript presets. When I changed it to ts-loader issue dissapeared.

It's probably because resolving of decorators is other in both cases.

```
export function fixedInject(token: InjectionToken<any>): (target: any, propertyKey: string | symbol, parameterIndex: number) => any {
    return (target: any, propertyKey: string | symbol, parameterIndex: number) => {
        inject(token)(target, propertyKey, parameterIndex);
        const params = Reflect.getMetadata("design:paramtypes", target) || [];
        const injectionTokens = Reflect.getOwnMetadata("injectionTokens", target) || {};
        Object.keys(injectionTokens).forEach(function (key) {
            params[+key] = injectionTokens[key];
        });
    }
}
```

After some tries I've managed that generating keys for `injectionTokens ` is working. 
It's for sure related to `babel-plugin-transform-typescript-metadata` and `@babel/typescript`.

**Comment by Xapphire13** [comment]
Closing as per discussion above

**Comment by cypherix93** [comment]
I actually ran into this same issue and found out that I could just pass on the reflection metadata onto the new constructor. Now the new constructor gets called with the injected dependencies. Not sure if this is the correct approach, but it seems to work for now. See below:

```typescript
const INJECTION_TOKEN_METADATA_KEY = 'injectionTokens';

export function MyDecorator(): ClassDecorator {
    return ((target: { new(...args: any[]): any }) => {
        const original = target;

        const injectionTokensMetadata = Reflect.getOwnMetadata(INJECTION_TOKEN_METADATA_KEY, original) || {};

        const wrapper = function (...args: any[]) {
                // args here have the injected constructor dependencies
        };

        wrapper.prototype = original.prototype;

        Reflect.defineMetadata(INJECTION_TOKEN_METADATA_KEY, injectionTokensMetadata, wrapper);

        return wrapper;
    }) as ClassDecorator;
}
```

Caveat is that I have to register `MyDecorator` _below_ the tsyringe one, so that tsyringe registers my overriden constructor reference. For example:

```typescript
@singleton()
@MyDecorator()
export class MyService implements IMyService {

    constructor(
        @inject('MyOtherService') private _myOtherService: IMyOtherService
    ) {
    }
}
```

And then I'm doing

```typescript
// registration
container.register('MyService', MyService);

// resolution somewhere else
container.resolve<IMyService>('MyService');
```
