### ISSUE TITLE
How to resolve dependencies based on type?

### ISSUE THREAD

**Issue by joe307bad** [microsoft/tsyringe#57]
If I have two classes:
```
class Foo (
    contructor(@inject("IValidator") private validator: IValidator<Foo>) {}
)

class Bar (
    contructor(@inject("IValidator") private validator: IValidator<Bar>) {}
)
```

Can I have two separate instances of `validator` in this situation? Could I have a `BarValidator` class and a `FooValidator` class?

**Comment by skiptirengu** [comment]
Typescript interfaces are not objects like classes are. Trying to bind a value to a interface will cause a `"Interface" only refers to a type, but is being used as a value here` error. 

That's why we can't use `@inject(IValidator)`, and instead we need to use `@inject("IValidator")` (as string).

Unfortunately, due to this limitation, the only solution is to register two distinct types on the container so you can resolve them later on.

```ts
container.register<IValidator<Foo>>("IValidator<Foo>", { useValue: validatorFooInstance });
container.register<IValidator<Bar>>("IValidator<Bar>", { useValue: validatorBarInstance });
```

**Comment by joe307bad** [comment]
Thanks!
