### ISSUE TITLE
Allow @inject() to use with property.

### ISSUE THREAD

**Issue by dilame** [microsoft/tsyringe#80]
**Is your feature request related to a problem? Please describe.**

```ts
class Child extends Parent {
  constructor(@inject('something') private something: string) {
    super(); // This is required since this class has Parent. 
  }
}
```

It's not convenient to describe deps in constructor if i have to call super(). I'd want to inject deps right in property

**Alternate solutions**

```ts
class Child extends Parent {
  @inject('something') private something: string
}
```

Much more cleaner

**Comment by Xapphire13** [comment]
Unfortunately property injection is something we explicitly don't want to support with this library. I'll update the docs to reflect this.

**Comment by dilame** [comment]
Could you please explain the reason?

**Comment by MeltingMosaic** [comment]
The main reason is that so far, property injection isn't necessary, and results in the ability to do the same thing 2 different ways, which I'd like to avoid.

Also, on a lesser point, from the genesis of this project, we (@Xapphire13 and I) philosophically only wanted constructor injection (it's even in the description of the project) in order to keep things simple and allow us to focus on doing a few things well.

**Comment by fjswhl** [comment]
if you still want to use property injection, you can create a decorator like this
```typescript
import { InjectionToken, container, inject } from 'tsyringe'

export type ForwardRefFn<T> = () => InjectionToken<T>

export function AutoWired<T>(target: any, propertyKey: string | symbol): void
export function AutoWired<T>(token: InjectionToken<T> | ForwardRefFn<T>): (target: any, propertyKey: string | symbol, parameterIndex?: number) => void
export function AutoWired<T>(token?: InjectionToken<T> | ForwardRefFn<T>, propertyKey?: string | symbol): ((target: any, propertyKey: string | symbol, parameterIndex?: number) => void) | void {

    if (typeof token === 'function') {
        return (target: any, propertyKey: string | symbol) => {
            Object.defineProperty(target, propertyKey, {
                get: () => {
                    const type = (token as ForwardRefFn<T>)()
                    return container.resolve(type)
                }
            })
        }
    } else if (token && propertyKey) {
        const type = Reflect.getMetadata('design:type', token, propertyKey)
        if (type === undefined) {
            // tslint:disable-next-line:no-console
            throw new Error(`failed to get design type of ${(token as any).constructor.name}'s ${String(propertyKey)}`)
        }
        Object.defineProperty(token, propertyKey, {
            get: () => {
                return container.resolve(type)
            }
        })
    } else {
        return (target: any, propertyKey: string | symbol, index?: number) => {
            if (index !== undefined) {
                return inject(token!)(target, propertyKey, index)
            } else {
                if (token) {
                    Object.defineProperty(target, propertyKey, {
                        get: () => {
                            return container.resolve(token)
                        }
                    })
                }
            }
        }
    }
}
```

and usage example
```typescript
@singleton
class Foo {}

class Bar {
  @AutoWired foo!: Foo
}
```

Anyway I prefer constructor injection

**Comment by Areen3** [comment]
However, I can see why it is worth injecting with property
the following case:
you have a controller in anglar, which injects services managed by an angular injector in the constructor
in this case, in order to inject a class created in pure typescript (which is sometimes used on the backend or in node), it should be injected as property

so in the shared part (used by frontend and backend) we have a class decorated by TSyringe
in the frontend part of the angular, we inject it through properets (because that's the only way we can)
in part, e.g. nest.js, we inject using property (because that's the only way we can)

Your decorator example solves the problem, but please consider adding this decorator to your library

**Comment by mmospanenko** [comment]
yes, with RxJs it is incredibly useful, we should get value before controller run and use it in reactive definitions. This is why Angular added @inject and moved away from controller auto-injections. But yes, for any others cases controller is great place
