### ISSUE TITLE
A suggestion about inheritance

### ISSUE THREAD

**Issue by unlocomqx** [Microsoft/tsyringe#9]
The issue is that I have duplicate code when using inheritance

Here's a sample code from the parent class
```
@injectable()
export class DynamicEquation {

   public constructor (
    protected ajax: Ajax,
    protected tools: Tools,
    protected pubsub: PubSub,
    protected messenger: Messenger,
  ) {
  }

}
```
and then the child class
```
@injectable()
export class PriceEquation extends DynamicEquation {

  public constructor (
    protected ajax: Ajax,
    protected tools: Tools,
    protected pubsub: PubSub,
    protected messenger: Messenger,
  ) {
    super(ajax, tools, pubsub, messenger)
  }

}
```
A lot of the same code is repeated and I have to modify several files when I want to add a new dependency

Is there a way to remove the child constructor altogether and still have dependencies resolved?
Would it be a good behaviour to implement in tsyringe if not currently feasible?

**Comment by Xapphire13** [comment]
This case is actually already supported, see [this test case](https://github.com/Microsoft/tsyringe/blob/3fa3816c9bc755fe9b353b5ef434dec0a7fe8b1d/tests/auto-injectable.test.ts#L48-L67) for an example.

The basic flow is to have your child class only take in what it needs, and in its constructor only call `super()`. Since at runtime, the constructor of the parent has been replaced with one that has it's dependencies auto-injected.

**Comment by unlocomqx** [comment]
Thank you for the valuable information, this will make my code much lighter and cleaner. Awesome!
